### ISSUE TITLE
Will you be my friend?

### ISSUE THREAD

**Issue by rilysh** [ZeroAurora/ZeroAurora#1]
Hi!...
will you be my friend?
你愿意做我的朋友吗？

**Comment by ZeroAurora** [comment]
抱歉回复晚了！如果你不介意的话，可以说说为什么想找我交流吗？如果觉得这里不太方便的话，可以直接给我发邮件的。

**Comment by rilysh** [comment]
Hi! Sorry for making the request...I was so sad and wanted a friend to talk to, and then I found you on my feed, that's why!

抱歉回复晚了！如果你不介意的话，可以说说为什么想找我交流吗？如果觉得这里不太方便的话，可以直接给我发邮件的。

**Comment by ZeroAurora** [comment]
可以邮件发我？我很乐意当一个树洞（虽然可能不会怎么回复，但是说出来总是好的）

**Comment by ghost** [comment]
@rilysh I would! let's become! add meee!!!!! it's `ophura` (user-id: `1258846993456038019`)!

ahahhehehhahaahlkebHBI&UQ!@@@<M!

**Comment by rilysh** [comment]
@8chan-co hi, tysm, i've send you friend request!

**Comment by ZeroAurora** [comment]
uwu
zeroaurora9472 at discord if you want. though I'm not viewing that platform often (I'm in China you know)
